import Image from "next/image";
import { ArrowLeft, ArrowRight, MapPin } from "lucide-react";
import { FadeIn, StaggerContainer, StaggerItem } from "@/components/ui/FadeIn";
import { Button } from "@/components/ui/Button";
import type { FeaturedProject } from "@/types";

export function BrigadeResidentialDetails({ project }: { project: FeaturedProject }) {
  return (
    <>
      <section className="bg-navy-gradient pt-32 pb-14 text-white md:pt-40 md:pb-20">
        <div className="container-xl px-6 lg:px-12">
          <FadeIn>
            <a href="/projects" className="inline-flex items-center gap-2 text-sm text-white/70 transition-colors hover:text-white"><ArrowLeft size={16} /> All projects</a>
            <div className="mt-8 flex flex-wrap items-center gap-4">
              <span className="relative h-14 w-24 overflow-hidden rounded-lg bg-white p-1"><Image src="/builders/brigade-group.jpg" alt="Brigade Group logo" fill className="object-contain" sizes="96px" /></span>
              <div><p className="text-xs font-semibold uppercase tracking-[0.25em] text-gold">Brigade Group · Hyderabad</p><h1 className="mt-2 font-display text-4xl font-semibold md:text-6xl">{project.name}</h1></div>
            </div>
            <p className="mt-5 flex items-center gap-2 text-sm text-white/75 md:text-base"><MapPin size={17} />{project.location}</p>
            <p className="mt-5 max-w-3xl text-base leading-relaxed text-white/75 md:text-lg">{project.overview}</p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row">
              <Button href="/contact" size="lg">Ask about this project <ArrowRight size={17} /></Button>
              <a href="#amenities" className="inline-flex items-center justify-center rounded-full border border-white/40 px-7 py-4 text-sm font-semibold text-white transition-colors hover:bg-white/10">Explore amenities and nearby places</a>
              {project.locationLink && <a href={project.locationLink} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center rounded-full border border-white/40 px-7 py-4 text-sm font-semibold text-white transition-colors hover:bg-white/10">Open Google Maps</a>}
            </div>
          </FadeIn>
          {project.coverImage && <FadeIn delay={0.1}><div className="relative mt-10 aspect-[16/8] overflow-hidden rounded-xl2 border border-white/15 bg-white/10 shadow-card"><Image src={project.coverImage} alt={`${project.name} brochure cover photo`} fill priority sizes="(max-width: 1024px) 100vw, 1100px" className="object-cover" unoptimized /></div></FadeIn>}
        </div>
      </section>

      {project.quickFacts && <section className="bg-offwhite py-8"><div className="container-xl grid grid-cols-2 gap-4 px-6 sm:grid-cols-2 lg:grid-cols-4 lg:px-12">{project.quickFacts.map((fact) => <div key={fact.label} className="rounded-xl bg-white p-5 shadow-card"><p className="text-xs font-semibold uppercase tracking-wide text-gold-dark">{fact.label}</p><p className="mt-2 text-sm font-medium leading-relaxed text-navy">{fact.value}</p></div>)}</div></section>}

      {project.indicativeStartingPrice && <section className="section-pad bg-white"><div className="container-xl grid gap-7 px-6 md:grid-cols-[1fr_auto] md:items-center lg:px-12"><div><span className="text-xs font-semibold uppercase tracking-[0.25em] text-gold-dark">Indicative starting price</span><h2 className="mt-3 font-display text-3xl font-semibold text-navy md:text-4xl">{project.indicativeStartingPrice}</h2><p className="mt-3 max-w-3xl text-sm leading-relaxed text-slate/70">{project.priceNote}</p></div><Button href="/contact" size="lg">Request current pricing <ArrowRight size={17} /></Button></div></section>}

      {project.amenityGroups && <section id="amenities" className="section-pad scroll-mt-24 bg-offwhite"><div className="container-xl px-6 lg:px-12"><FadeIn><div className="mb-8 max-w-2xl"><span className="text-xs font-semibold uppercase tracking-[0.25em] text-gold-dark">From the supplied master plan</span><h2 className="mt-3 font-display text-3xl font-semibold text-navy md:text-4xl">Amenities and plan legend</h2><p className="mt-3 text-sm leading-relaxed text-slate/70">Numbers follow the legend on the Brigade brochure plan.</p></div></FadeIn><div className="space-y-8">{project.amenityGroups.map((group) => <div key={group.category}><h3 className="mb-4 font-display text-2xl font-semibold text-navy">{group.category}</h3><StaggerContainer className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">{group.amenities.map((amenity, index) => { const match = amenity.match(/^(\d{1,2})\.\s*(.*)$/); return <StaggerItem key={`${group.category}-${amenity}`}><div className="flex h-full items-start gap-3 rounded-xl border border-navy/10 bg-white p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-gold/20 text-xs font-semibold text-navy">{match?.[1] ?? index + 1}</span><p className="pt-1 text-sm leading-relaxed text-slate/80">{match?.[2] ?? amenity}</p></div></StaggerItem>;})}</StaggerContainer></div>)}</div></div></section>}

      {project.masterLayout && <section id="master-plan" className="section-pad scroll-mt-24 bg-white"><div className="container-xl px-6 lg:px-12"><FadeIn><div className="mb-8 max-w-2xl"><span className="text-xs font-semibold uppercase tracking-[0.25em] text-gold-dark">Site plan</span><h2 className="mt-3 font-display text-3xl font-semibold text-navy md:text-4xl">Master plan with legend</h2><p className="mt-3 text-sm leading-relaxed text-slate/70">Select the plan to open the brochure image at a larger size.</p></div><a href={project.masterLayout} target="_blank" rel="noopener noreferrer" className="block overflow-hidden rounded-xl2 border border-navy/10 bg-offwhite p-2 shadow-card"><Image src={project.masterLayout} alt={`${project.name} master plan and amenity legend`} width={2200} height={1800} className="h-auto w-full rounded-lg" unoptimized /></a></FadeIn></div></section>}

      {project.nearbyPlaces && <section className="section-pad bg-offwhite"><div className="container-xl px-6 lg:px-12"><FadeIn><div className="mb-8 max-w-2xl"><span className="text-xs font-semibold uppercase tracking-[0.25em] text-gold-dark">Moti Nagar · Hyderabad</span><h2 className="mt-3 font-display text-3xl font-semibold text-navy md:text-4xl">Nearby places</h2><p className="mt-3 text-sm leading-relaxed text-slate/70">Neighbourhood names and distances shown in the supplied location screenshots. Distances and travel times may vary by route.</p></div></FadeIn><div className="grid gap-5 md:grid-cols-2">{project.nearbyPlaces.map((group) => <article key={group.category} className="rounded-xl2 border border-navy/10 bg-white p-6"><h3 className="flex items-center gap-2 font-display text-xl font-semibold text-navy"><MapPin size={17} className="text-gold-dark" />{group.category}</h3><ul className="mt-4 flex flex-wrap gap-2">{group.places.map((place) => <li key={place} className="rounded-full bg-offwhite px-3 py-2 text-xs leading-relaxed text-slate/75">{place}</li>)}</ul></article>)}</div>{project.locationMap && <div className="mt-8"><h3 className="mb-3 font-display text-xl font-semibold text-navy">Location map</h3><a href={project.locationMap} target="_blank" rel="noopener noreferrer" className="block overflow-hidden rounded-xl2 border border-navy/10 bg-white p-2 shadow-card"><Image src={project.locationMap} alt={`${project.name} location map from its brochure`} width={1800} height={1200} className="h-auto w-full rounded-lg" unoptimized /></a></div>}</div></section>}

      {project.sampleVideos?.length ? <section className="section-pad bg-white"><div className="container-xl px-6 lg:px-12"><FadeIn><div className="mb-8 max-w-2xl"><span className="text-xs font-semibold uppercase tracking-[0.25em] text-gold-dark">Project video</span><h2 className="mt-3 font-display text-3xl font-semibold text-navy md:text-4xl">Take a closer look</h2></div></FadeIn><div className="grid gap-5 md:grid-cols-2">{project.sampleVideos.map((video) => <div key={video.videoId}><p className="mb-2 text-sm font-medium text-navy">{video.label}</p><div className="aspect-video overflow-hidden rounded-xl2 bg-navy/5"><iframe src={`https://www.youtube-nocookie.com/embed/${video.videoId}`} title={`${project.name} ${video.label}`} className="h-full w-full" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen /></div></div>)}</div></div></section> : null}

      <section className="bg-navy-gradient py-16 text-white md:py-20"><div className="container-xl px-6 text-center lg:px-12"><FadeIn><h2 className="font-display text-3xl font-semibold md:text-4xl">Explore {project.name}</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-relaxed text-white/70">Contact Kairos for current availability, pricing and a guided project visit.</p><div className="mt-7 flex justify-center"><Button href="/contact" size="lg">Enquire about this project <ArrowRight size={17} /></Button></div><p className="mx-auto mt-8 max-w-4xl text-xs leading-relaxed text-white/55">Project details, images, nearby places and prices are based on supplied materials and may change. Confirm current availability, final specifications, approvals, pricing and terms with Brigade Group.</p></FadeIn></div></section>
    </>
  );
}
